name = "Blio"
uuid = "87855aa7-8b24-49b4-b316-97c011f78d17"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.6.6+dev"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[extensions]
DataFramesBlioExt = "DataFrames"
HDF5FilterbankExt = "HDF5"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
DataFrames = "1.0.0"
HDF5 = "0.16.14,0.17"
